config/routes.rb
Badger::Application.routes.draw do
  resources :badges, :except => :show
  resources :users
  resource :user_session

  match '/email/new/:id' => 'email#new', :as => :new_email
  match '/email/send/:id' => 'email#send', :as => :send_email

  
  root :to => "badges#index"
  
  match '/media(/:dragonfly)', :to => Dragonfly[:images]
  

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user.admin?
      can :manage, :all
    else
      can :read, :all
    end
  end
end

app/models/badge.rb
class Badge < ActiveRecord::Base
  image_accessor :image
  
  validates_presence_of :name
  validates_uniqueness_of :name
end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_authentic
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper :all
  helper_method :current_user_session, :current_user

  rescue_from CanCan::AccessDenied do |exception|
    flash[:error] = "DENIED! Booya!"
    redirect_to root_url
  end

  private
    def current_user_session
      return @current_user_session if defined?(@current_user_session)
      @current_user_session = UserSession.find
    end

    def current_user
      return @current_user if defined?(@current_user)
      @current_user = current_user_session && current_user_session.user
    end

    def require_user
      unless current_user
        store_location
        flash[:notice] = "You must be logged in to access this page"
        redirect_to new_user_session_url
        return false
      end
    end

    def require_no_user
      if current_user
        store_location
        flash[:notice] = "You must be logged out to access this page"
        redirect_to account_url
        return false
      end
    end
    
    def store_location
      session[:return_to] = request.request_uri
    end
    
    def redirect_back_or_default(default)
      redirect_to(session[:return_to] || default)
      session[:return_to] = nil
    end
end

app/controllers/badges_controller.rb
class BadgesController < ApplicationController
  load_and_authorize_resource :except => :index

  def index
    per_page = 10

    @page = params[:page].to_i
    @page = (@page > 1) ? @page : 1
    
    @badges = Badge.limit(per_page).offset((@page - 1) * per_page)
    @total_pages = (Badge.count.to_f/per_page).ceil
  end
  
  def create
    @badge = Badge.new(params[:badge])
    if @badge.save
      flash[:success] = "Your badge is home"
      redirect_to badges_path
    else
      debugger
      flash[:error] = "Stuff was wrong in your badge stuff"
      render :action => "new"
    end
  end
  
  def new
    @badge = Badge.new
  end
  
  def edit
    @badge = Badge.find(params[:id])
  end
  
  def update
    @badge = Badge.find(params[:id])
    if @badge.update_attributes(params[:badge])
      flash[:success] = "Badge updated"
      redirect_to badges_path
    else
      flash[:error] = "Whoops, looks like something was wrong with that badge..."
      render :action => "edit"
    end
  end
  
  def destroy
    @badge = Badge.find(params[:id])
    @badge.destroy
    flash[:success] = "Badge be gone!"
    redirect_to badges_path
  end
end

app/controllers/email_controller.rb
class EmailController < ApplicationController
  def new
    @badge = Badge.find(params[:id])
  end
  
  def send
    @badge = Badge.find(params[:id])
    BadgeMailer.badge_and_comment(@badge, params[:email], params[:message]).deliver
    flash[:success] = "Email has been sent to #{params[:email]}"
    redirect_to root_path
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  def new
    @user_session = UserSession.new
  end

  def create
    @user_session = UserSession.new(params[:user_session])
    if @user_session.save
      flash[:success] = "Logged in"
      redirect_back_or_default root_path
    else
      flash[:error] = "Something was wrong with your login info"
      render :action => :new
    end
  end

  def destroy
    current_user_session.destroy
    flash[:success] = "Logged out"
    redirect_back_or_default root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_no_user, :only => [:new, :create]
  before_filter :require_user, :only => [:show, :edit, :update]
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save
      flash[:success] = "Account registered!"
      redirect_back_or_default root_path
    else
      render :action => :new
    end
  end
  
  def show
    @user = @current_user
  end

  def edit
    @user = @current_user
  end
  
  def update
    @user = @current_user # makes our views "cleaner" and more consistent
    if @user.update_attributes(params[:user])
      flash[:success] = "Account updated!"
      redirect_to root_path
    else
      render :action => :edit
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def error_for(record, field, err_string)
    if !record.errors[field].empty?
      return "<div class='error'>#{err_string}</div>".html_safe
    end
  end
end

app/helpers/badges_helper.rb
module BadgesHelper
end

app/helpers/email_helper.rb
module EmailHelper
end

app/views/badges/_form.html.erb
<%= form_for @badge, :html => {:multipart => true} do |f| %>
  <div class="labelAndField">
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= error_for @badge, :name, "It needs a unique name" %>
  </div>
  
  <div class="labelAndField">
    <%= f.label :image %>
    <% if @badge.image_uid? %>
      <div><%= image_tag @badge.image.url %></div>
    <% end %>
    <%= f.file_field :image %>
    <%= error_for @badge, :image, "You have to provide an image for it" %>
  </div>
  
  <div>
    <% if @badge.new_record? %>
      <%= submit_tag "Add badge stat!" %>
    <% else %>
      <%= submit_tag "Update the badge before I get angry!" %>
    <% end %>
  </div>
<% end %>

<% if :back %>
  <p>Or, <%= link_to "go back from whence you came", :back %></p>
<% end %>

app/views/badges/edit.html.erb
<h2>Change stuff, if you really want to:</h2>

<%= render :partial => "form" %>

app/views/badges/index.html.erb
<h2>Here's all the badges, and stuff:</h2>

<ul class="badges">
  <% @badges.each do |b| %>
      <li>
          <%= image_tag b.image.url %>
          <div class="name">
            <span><%= b.name %></span>
            <% if current_user %>
              <div>
                <% if can? :manage, b %>
                  <%= link_to "Edit", edit_badge_path(b) %> | 
                  <%= link_to "Kill", badge_path(b), :confirm => "Be sure, bro", :method => :delete %> |
                <% end %>
                <%= link_to "Email", new_email_path(b) %>
              </div>
            <% end %>
            </div>
      </li>
  <% end %>
</ul>

<% if @total_pages > 1 %>
  <p>Go to Page:</p>
  <ul class="pages">
    <% 1.upto(@total_pages).each do |p| %>
      <li>
          <% if @page != p %>
            <a href="/?page=<%= p %>"><%= p %></a>
          <% else %>
            <%= p %>
          <% end %>
      </li>
    <% end %>
  </ul>
  <div class="clear"></div>
<% end %>

<% if current_user && can?(:create, Badge) %>
  <%= link_to "Wanna create a badge?", new_badge_path %>
<% end %>

app/views/badges/new.html.erb
<h2>Make a new badge, or whatever:</h2>

<%= render :partial => "form" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Badger</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
<h1><a href="/">Badger!</a></h1>

<% if flash[:error] %>
  <%= image_tag "badger.jpg" %>
  <div class="errors">
    <p><%= flash[:error] %></p>
  </div>
<% elsif flash[:success] %>
  <div class="success">
      <p><%= flash[:success] %></p>
  </div>
<% end %>

<% if current_user %>
  <p class="loggedIn">
    Logged in as <span class="email"><%= current_user.email %></span>
  </p>
  <p><%= link_to "Logout", user_session_path, :method => :delete %></p>
<% else %>
  <p><%= link_to "Login", new_user_session_path %> or <%= link_to "Create account", new_user_path %></p>
<% end %>

<%= yield %>

</body>
</html>

app/views/user_sessions/new.html.erb
<h2>Login, if you please</h2>

<%= form_for @user_session, :url => user_session_path do |f| %>
  <%= f.label :email %><br />
  <%= f.text_field :email %><br />
  <%= error_for @user_session, :email, "Email must be filled in and valid" %>
  <br />
  <%= f.label :password %><br />
  <%= f.password_field :password %><br />
  <%= error_for @user_session, :password, "Password must be filled in and valid" %>
  <br />
  <%= f.submit "Login" %>
<% end %>

app/views/users/new.html.erb
<h2>Create an account if you're up to the challenge</h2>

<%= form_for @user do |f| %>
  <%= f.label :email %><br />
  <%= f.text_field :email %><br />
  <%= error_for @user, :email, "Email must be filled in and valid" %>
  <br />
  <%= f.label :password %><br />
  <%= f.password_field :password %><br />
  <%= error_for @user, :password, "Password must be filled in and valid" %>
  <br />
  <%= f.label :password_confirmation %><br />
  <%= f.password_field :password_confirmation %><br />
  <%= error_for @user, :password_confirmation, "Password confirmation must be filled in and match password" %>
  <br />
  <%= f.submit "Create User" %>
<% end %>